export const ordersManagementData = [
    {
        key: '1',
        orderid: '85464',
        customername: 'Mike Jackson',
        status: 'in_transit',
        item: 3,
        deliveryperson: 'Tuhin Ahemd',
        deliveryType: "car",
        date: '09-01-24',
        bill: 253,
        senderType: 'Non-Professional',
    },
    {
        key: '2',
        orderid: '85465',
        customername: 'Delwar Hossain',
        status: 'requested',
        item: 3,
        deliveryperson: 'Paran Ahemd',
        deliveryType: "bike",
        date: '10-01-24',
        bill: 200,
        senderType: 'Non-Professional',
    },
    {
        key: '3',
        orderid: '85466',
        customername: 'Rahad Ullah',
        status: 'accepted',
        item: 3,
        deliveryperson: 'Jack Duell',
        deliveryType: "person",
        date: '12-01-24',
        bill: 500,
        senderType: 'Non-Professional',
    },
    {
        key: '4',
        orderid: '85467',
        customername: 'Sarah Johnson',
        status: 'in_transit',
        item: 2,
        deliveryperson: 'Paul Smith',
        deliveryType: "truck",
        date: '13-01-24',
        bill: 350,
        senderType: 'Professional',
    },
    {
        key: '5',
        orderid: '85468',
        customername: 'Martha Lee',
        status: 'delivered',
        item: 4,
        deliveryperson: 'Linda Taylor',
        deliveryType: "car",
        date: '14-01-24',
        bill: 420,
        senderType: 'Non-Professional',
    },
    {
        key: '6',
        orderid: '85469',
        customername: 'Robert Brown',
        status: 'requested',
        item: 1,
        deliveryperson: 'David Wilson',
        deliveryType: "bicycle",
        date: '15-01-24',
        bill: 150,
        senderType: 'Non-Professional',
    },
    {
        key: '7',
        orderid: '85470',
        customername: 'Emily Davis',
        status: 'in_transit',
        item: 5,
        deliveryperson: 'Chris Green',
        deliveryType: "car",
        date: '16-01-24',
        bill: 600,
        senderType: 'Non-Professional',
    },
    {
        key: '8',
        orderid: '85471',
        customername: 'John Carter',
        status: 'delivered',
        item: 3,
        deliveryperson: 'Tom Brown',
        deliveryType: "truck",
        date: '17-01-24',
        bill: 550,
        senderType: 'Professional',
    },
    {
        key: '9',
        orderid: '85472',
        customername: 'Ava White',
        status: 'accepted',
        item: 2,
        deliveryperson: 'Harry Black',
        deliveryType: "bike",
        date: '18-01-24',
        bill: 180,
        senderType: 'Non-Professional',
    },
    {
        key: '10',
        orderid: '85473',
        customername: 'Sophia King',
        status: 'pending',
        item: 4,
        deliveryperson: 'Oliver Prince',
        deliveryType: "car",
        date: '19-01-24',
        bill: 480,
        senderType: 'Non-Professional',
    },
    {
        key: '11',
        orderid: '85474',
        customername: 'Liam Scott',
        status: 'delivered',
        item: 2,
        deliveryperson: 'Emma Queen',
        deliveryType: "truck",
        date: '20-01-24',
        bill: 300,
        senderType: 'Professional',
    },
    {
        key: '12',
        orderid: '85475',
        customername: 'Mia Young',
        status: 'requested',
        item: 1,
        deliveryperson: 'Noah Stone',
        deliveryType: "bike",
        date: '21-01-24',
        bill: 120,
        senderType: 'Non-Professional',
    },
    {
        key: '13',
        orderid: '85476',
        customername: 'Lucas Wright',
        status: 'pending',
        item: 3,
        deliveryperson: 'Ella Blue',
        deliveryType: "person",
        date: '22-01-24',
        bill: 340,
        senderType: 'Non-Professional',
    },
    {
        key: '14',
        orderid: '85477',
        customername: 'Amelia Hill',
        status: 'accepted',
        item: 5,
        deliveryperson: 'Jack Woods',
        deliveryType: "truck",
        date: '23-01-24',
        bill: 600,
        senderType: 'Professional',
    },
    {
        key: '15',
        orderid: '85478',
        customername: 'Mason Turner',
        status: 'in_transit',
        item: 2,
        deliveryperson: 'Lily Rivers',
        deliveryType: "bicycle",
        date: '24-01-24',
        bill: 250,
        senderType: 'Non-Professional',
    },
    {
        key: '16',
        orderid: '85479',
        customername: 'Harper Adams',
        status: 'delivered',
        item: 4,
        deliveryperson: 'Owen Field',
        deliveryType: "car",
        date: '25-01-24',
        bill: 420,
        senderType: 'Non-Professional',
    },
    {
        key: '17',
        orderid: '85480',
        customername: 'Evelyn Perry',
        status: 'in_transit',
        item: 3,
        deliveryperson: 'Henry Lane',
        deliveryType: "truck",
        date: '26-01-24',
        bill: 500,
        senderType: 'Professional',
    },
    {
        key: '18',
        orderid: '85481',
        customername: 'Aiden Baker',
        status: 'delivered',
        item: 1,
        deliveryperson: 'Leah Marsh',
        deliveryType: "bike",
        date: '27-01-24',
        bill: 130,
        senderType: 'Non-Professional',
    },
    {
        key: '19',
        orderid: '85482',
        customername: 'Ella Foster',
        status: 'pending',
        item: 5,
        deliveryperson: 'Samuel Creek',
        deliveryType: "car",
        date: '28-01-24',
        bill: 570,
        senderType: 'Non-Professional',
    },
    {
        key: '20',
        orderid: '85483',
        customername: 'Chloe Hayes',
        status: 'accepted',
        item: 2,
        deliveryperson: 'Mason Shore',
        deliveryType: "truck",
        date: '29-01-24',
        bill: 310,
        senderType: 'Professional',
    },
    {
        key: '21',
        orderid: '85484',
        customername: 'Henry Ford',
        status: 'requested',
        item: 1,
        deliveryperson: 'Isla Waters',
        deliveryType: "bicycle",
        date: '30-01-24',
        bill: 170,
        senderType: 'Non-Professional',
    },
    {
        key: '22',
        orderid: '85485',
        customername: 'Grace Wells',
        status: 'pending',
        item: 4,
        deliveryperson: 'Leo Brook',
        deliveryType: "car",
        date: '31-01-24',
        bill: 460,
        senderType: 'Non-Professional',
    },
    {
        key: '23',
        orderid: '85486',
        customername: 'Zoe Palmer',
        status: 'delivered',
        item: 3,
        deliveryperson: 'Ruby Hill',
        deliveryType: "truck",
        date: '01-02-24',
        bill: 490,
        senderType: 'Professional',
    },
    {
        key: '24',
        orderid: '85487',
        customername: 'Victoria Snow',
        status: 'requested',
        item: 2,
        deliveryperson: 'Finn Stream',
        deliveryType: "bike",
        date: '02-02-24',
        bill: 210,
        senderType: 'Non-Professional',
    },
    {
        key: '25',
        orderid: '85488',
        customername: 'Hannah Stone',
        status: 'in_transit',
        item: 4,
        deliveryperson: 'Oscar Lake',
        deliveryType: "car",
        date: '03-02-24',
        bill: 430,
        senderType: 'Non-Professional',
    }
  ];
  