export const ordersManagementData = [
  {
      key: '1',
      orderid: '85464',
      customername: 'Mike Jackson',
      status: 'In-Transit',
      item: 3,
      deliveryperson: 'Tuhin Ahemd',
      shippingtype: "Car",
      date: '09-01-24',
      bill: 253,
  },
  {
      key: '2',
      orderid: '85465',
      customername: 'Delwar Hossain',
      status: 'Canceled',
      item: 3,
      deliveryperson: 'Paran Ahemd',
      shippingtype: "Bike",
      date: '10-01-24',
      bill: 200,
  },
  {
      key: '3',
      orderid: '85466',
      customername: 'Rahad Ullah',
      status: 'Delivered',
      item: 3,
      deliveryperson: 'Jack Duell',
      shippingtype: "Car",
      date: '12-01-24',
      bill: 500,
  },
  {
      key: '4',
      orderid: '85467',
      customername: 'Sarah Johnson',
      status: 'In-Transit',
      item: 2,
      deliveryperson: 'Paul Smith',
      shippingtype: "Truck",
      date: '13-01-24',
      bill: 350,
  },
  {
      key: '5',
      orderid: '85468',
      customername: 'Martha Lee',
      status: 'Delivered',
      item: 4,
      deliveryperson: 'Linda Taylor',
      shippingtype: "Car",
      date: '14-01-24',
      bill: 420,
  },
  {
      key: '6',
      orderid: '85469',
      customername: 'Robert Brown',
      status: 'Canceled',
      item: 1,
      deliveryperson: 'David Wilson',
      shippingtype: "Bike",
      date: '15-01-24',
      bill: 150,
  },
  {
      key: '7',
      orderid: '85470',
      customername: 'Emily Davis',
      status: 'In-Transit',
      item: 5,
      deliveryperson: 'Chris Green',
      shippingtype: "Car",
      date: '16-01-24',
      bill: 600,
  },
  {
      key: '8',
      orderid: '85471',
      customername: 'John Carter',
      status: 'Delivered',
      item: 3,
      deliveryperson: 'Tom Brown',
      shippingtype: "Truck",
      date: '17-01-24',
      bill: 550,
  },
  {
      key: '9',
      orderid: '85472',
      customername: 'Ava White',
      status: 'Canceled',
      item: 2,
      deliveryperson: 'Harry Black',
      shippingtype: "Bike",
      date: '18-01-24',
      bill: 180,
  },
  {
      key: '10',
      orderid: '85473',
      customername: 'Sophia King',
      status: 'In-Transit',
      item: 4,
      deliveryperson: 'Oliver Prince',
      shippingtype: "Car",
      date: '19-01-24',
      bill: 480,
  },
  {
      key: '11',
      orderid: '85474',
      customername: 'Liam Scott',
      status: 'Delivered',
      item: 2,
      deliveryperson: 'Emma Queen',
      shippingtype: "Truck",
      date: '20-01-24',
      bill: 300,
  },
  {
      key: '12',
      orderid: '85475',
      customername: 'Mia Young',
      status: 'Canceled',
      item: 1,
      deliveryperson: 'Noah Stone',
      shippingtype: "Bike",
      date: '21-01-24',
      bill: 120,
  },
  {
      key: '13',
      orderid: '85476',
      customername: 'Lucas Wright',
      status: 'In-Transit',
      item: 3,
      deliveryperson: 'Ella Blue',
      shippingtype: "Car",
      date: '22-01-24',
      bill: 340,
  },
  {
      key: '14',
      orderid: '85477',
      customername: 'Amelia Hill',
      status: 'Delivered',
      item: 5,
      deliveryperson: 'Jack Woods',
      shippingtype: "Truck",
      date: '23-01-24',
      bill: 600,
  },
  {
      key: '15',
      orderid: '85478',
      customername: 'Mason Turner',
      status: 'Canceled',
      item: 2,
      deliveryperson: 'Lily Rivers',
      shippingtype: "Bike",
      date: '24-01-24',
      bill: 250,
  },
  {
      key: '16',
      orderid: '85479',
      customername: 'Harper Adams',
      status: 'In-Transit',
      item: 4,
      deliveryperson: 'Owen Field',
      shippingtype: "Car",
      date: '25-01-24',
      bill: 420,
  },
  {
      key: '17',
      orderid: '85480',
      customername: 'Evelyn Perry',
      status: 'Delivered',
      item: 3,
      deliveryperson: 'Henry Lane',
      shippingtype: "Truck",
      date: '26-01-24',
      bill: 500,
  },
  {
      key: '18',
      orderid: '85481',
      customername: 'Aiden Baker',
      status: 'Canceled',
      item: 1,
      deliveryperson: 'Leah Marsh',
      shippingtype: "Bike",
      date: '27-01-24',
      bill: 130,
  },
  {
      key: '19',
      orderid: '85482',
      customername: 'Ella Foster',
      status: 'In-Transit',
      item: 5,
      deliveryperson: 'Samuel Creek',
      shippingtype: "Car",
      date: '28-01-24',
      bill: 570,
  },
  {
      key: '20',
      orderid: '85483',
      customername: 'Chloe Hayes',
      status: 'Delivered',
      item: 2,
      deliveryperson: 'Mason Shore',
      shippingtype: "Truck",
      date: '29-01-24',
      bill: 310,
  },
  {
      key: '21',
      orderid: '85484',
      customername: 'Henry Ford',
      status: 'Canceled',
      item: 1,
      deliveryperson: 'Isla Waters',
      shippingtype: "Bike",
      date: '30-01-24',
      bill: 170,
  },
  {
      key: '22',
      orderid: '85485',
      customername: 'Grace Wells',
      status: 'In-Transit',
      item: 4,
      deliveryperson: 'Leo Brook',
      shippingtype: "Car",
      date: '31-01-24',
      bill: 460,
  },
  {
      key: '23',
      orderid: '85486',
      customername: 'Zoe Palmer',
      status: 'Delivered',
      item: 3,
      deliveryperson: 'Ruby Hill',
      shippingtype: "Truck",
      date: '01-02-24',
      bill: 490,
  },
  {
      key: '24',
      orderid: '85487',
      customername: 'Victoria Snow',
      status: 'Canceled',
      item: 2,
      deliveryperson: 'Finn Stream',
      shippingtype: "Bike",
      date: '02-02-24',
      bill: 210,
  },
  {
      key: '25',
      orderid: '85488',
      customername: 'Hannah Stone',
      status: 'In-Transit',
      item: 4,
      deliveryperson: 'Oscar Lake',
      shippingtype: "Car",
      date: '03-02-24',
      bill: 430,
  }
];
